// <auto-generated />
using System;
using ManagementOfPersonalAccountData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManagementOfPersonalAccountData.Migrations
{
    [DbContext(typeof(PersonalAccountContext))]
    [Migration("20240430071540_Resident")]
    partial class Resident
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ManagementOfPersonalAccountData.Models.PersonalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberPA")
                        .HasColumnType("TEXT");

                    b.Property<double>("RoomArea")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PersonalAccounts");
                });

            modelBuilder.Entity("ManagementOfPersonalAccountData.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fatherland")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccountId");

                    b.ToTable("Resident");
                });

            modelBuilder.Entity("ManagementOfPersonalAccountData.Models.Resident", b =>
                {
                    b.HasOne("ManagementOfPersonalAccountData.Models.PersonalAccount", null)
                        .WithMany("Residents")
                        .HasForeignKey("PersonalAccountId");
                });

            modelBuilder.Entity("ManagementOfPersonalAccountData.Models.PersonalAccount", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
